USE [IceCoffee.Template]
GO

--用户角色表
CREATE TABLE T_UserRole(
	Fk_UserId UNIQUEIDENTIFIER NOT NULL,				--用户Id
	Fk_RoleId UNIQUEIDENTIFIER NOT NULL,				--角色Id
	PRIMARY KEY(Fk_UserId,Fk_RoleId),
	FOREIGN KEY (Fk_UserId) REFERENCES T_User(Id) ON DELETE CASCADE,
	FOREIGN KEY (Fk_RoleId) REFERENCES T_Role(Id) ON DELETE CASCADE
);
GO
