USE [IceCoffee.Template]
GO

--用户角色表
CREATE TABLE T_UserRole(
	FK_UserId UNIQUEIDENTIFIER NOT NULL,				--用户Id
	FK_RoleId UNIQUEIDENTIFIER NOT NULL,				--角色Id
	PRIMARY KEY(FK_UserId,FK_RoleId),
	FOREIGN KEY (FK_UserId) REFERENCES T_User(Id) ON DELETE CASCADE,
	FOREIGN KEY (FK_RoleId) REFERENCES T_Role(Id) ON DELETE CASCADE
);
GO
