USE [IceCoffee.Template]
GO

--角色菜单表
CREATE TABLE T_RoleMenu(	
	Fk_RoleId UNIQUEIDENTIFIER NOT NULL,				--角色Id
	Fk_MenuId UNIQUEIDENTIFIER NOT NULL,				--菜单Id
	PRIMARY KEY(Fk_RoleId,Fk_MenuId),
	FOREIGN KEY (Fk_RoleId) REFERENCES T_Role(Id) ON DELETE CASCADE,
	FOREIGN KEY (Fk_MenuId) REFERENCES T_Menu(Id) ON DELETE CASCADE
);
GO
