USE [IceCoffee.Template]
GO

--角色菜单表
CREATE TABLE T_RoleMenu(	
	FK_RoleId UNIQUEIDENTIFIER NOT NULL,				--角色Id
	FK_MenuId UNIQUEIDENTIFIER NOT NULL,				--菜单Id
	PRIMARY KEY(FK_RoleId,FK_MenuId),
	FOREIGN KEY (FK_RoleId) REFERENCES T_Role(Id) ON DELETE CASCADE,
	FOREIGN KEY (FK_MenuId) REFERENCES T_Menu(Id) ON DELETE CASCADE
);
GO
