USE [IceCoffee.Template]
GO

--角色许可表
CREATE TABLE T_RolePermission(	
	FK_RoleId UNIQUEIDENTIFIER NOT NULL,					--角色Id
	FK_PermissionId UNIQUEIDENTIFIER NOT NULL,				--许可Id
	PRIMARY KEY(FK_RoleId,FK_PermissionId),
	FOREIGN KEY (FK_RoleId) REFERENCES T_Role(Id) ON DELETE CASCADE,
	FOREIGN KEY (FK_PermissionId) REFERENCES T_Permission(Id) ON DELETE CASCADE
);
GO
